### ISSUE TITLE
Cannot connect, many exceptions occurring

### ISSUE THREAD

**Issue by saveriodesign** [WhyKickAmooCow/dsp-docker-server#7]
Trying to deploy this in a Portainer LXC as provided by Proxmox Helper Scripts. My compose is as follows:

```yml
services:
  dsp-01:
    image: ghcr.io/whykickamoocow/dsp-docker-server:master
    container_name: dsp-01
    environment:
      SERVER_NAME:
      SERVER_PASSWORD:
      STEAM_USER:
      STEAM_PASSWORD:
      STEAM_2FA:
      # LAUNCH_ARGS: "-batchmode -nographics -server -newgame-cfg" # make new game after initial install
      # LAUNCH_ARGS: "-batchmode -nographics -server -load-latest"
    ports:
      - "8469:8469"
    volumes:
      - game:/game
      - /var/local/dsp-01:/save
    # command: "${STEAM_USER} ${STEAM_PASSWORD} ${STEAM_2FA}" # initial install
    # command: "update ${STEAM_USER} ${STEAM_PASSWORD} ${STEAM_2FA}" # update DSP
    # command: "update_mods" # update only mods
volumes:
  game:
```

The container successfully installs the game into the volume managed by Docker, however the container logs show an alarming stream of various exceptions, and I cannot connect from a machine on the same local network. The errors begin with a stream of library loading failures, of which these are non-exhaustive (there are perhaps 100+ such lines):

```
Fallback handler could not load library Z:/game/DSPGAME_Data/Mono/data-000075AF9A981850.dll
Fallback handler could not load library Z:/game/DSPGAME_Data/Mono/data-000075AF9AAD48A0.dll
Fallback handler could not load library Z:/game/DSPGAME_Data/Mono/data-000075AF9AC07BA0.dll
Fallback handler could not load library Z:/game/DSPGAME_Data/Mono/data-000075AF9A982950.dll
```

Then it hits a permissions issue which may be the core of my problem:

```
UnauthorizedAccessException: Access to the path "C:\users\dsp\Documents\Dyson Sphere Program\options.xml" is denied.
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001b7] in <2fa7a6a452ca43df998f07fd1486c0df>:IL_01B7 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <2fa7a6a452ca43df998f07fd1486c0df>:IL_0000 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at GameOption.SaveGlobal () [0x00005] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_0005 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
```

Finally, an unending stream of these two null reference exceptions wipe out any sign of the previous exceptions from my logs instantaneously. The first is roughly 5 times more common than the second. These continue until the container is stopped, and no save game is created in the mounted volume upon initial install or my "try to make a new save" configuration.

```
(Filename: <fce0e26bac414c5ebaccb0aaaac75063> Line: 0)
NullReferenceException: Object reference not set to an instance of an object
  at GameCamera.Logic () [0x00323] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_0323 
  at GameCamera.FrameLogic () [0x00000] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_0000 
  at GameCamera.LateUpdate () [0x00000] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_0000 
 
(Filename: <fce0e26bac414c5ebaccb0aaaac75063> Line: 0)
NullReferenceException: Object reference not set to an instance of an object
  at GuideMissionStandardMode.Skip (GameData _gameData) [0x00034] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_0034 
  at GameData.SkipStandardModeGuide () [0x00005] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_0005 
  at GameLoader.FixedUpdate () [0x000a6] in <fce0e26bac414c5ebaccb0aaaac75063>:IL_00A6 
```
